### ISSUE TITLE
Feedback Sprint 1 Datadashboard

### ISSUE THREAD

**Issue by nerdale** [MirEnovi/cdmx-2018-06-bc-core-am-data-dashboard#7]
Hola @MirEnovi y Compañera
He estado revisando el proyecto y tengo algunos comentarios:

1. @MirEnovi debes agregar como colaboradora a **AuraMelisa01**, es extremadamente necesario pues los issues van guiados hacia ambas.

2. De la mano del punto anterior veo que no realizaron los issues y milestones correspondientes al sprint 2 del proyecto, que pasó con eso?

3. Que pasó con el deploy a Github Pages? era uno de los requisitos para el demo del sprint 1

4. Felicitaciones por el uso de diagrama de flujo del proyecto y de pseudocódigo, les servirá muchisimo a no solo entender el como se debe ver y como se interactua, sino que también a entender de donde viene la información y como deben internamente conversar con la data para obtener lo que necesitan.

5. Ya veo un trabajo lógico pero les recomiendo comenzar a trabajar con la data a profundidad lo antes posible (se encontrarán con toda la lógica para jalar la información y hacer los cálculos) y plasmar tanto visual como funcionalmente lo que tienen pensado para el proyecto.

6. Recuerden utilizar HTML semántico `<header></header> <section></section> <aside></aside> <footer></footer> <article></article>`

7. Ojo con la indentación en el archivo **index.html** un código bien armado, ordenado y limpio es esencial para quien hace codereview, da feedback o colabora con el proyecto. Les dejo [esto](https://medium.com/@sthefany/qu%C3%A9-es-la-indentaci%C3%B3n-c9471f3ae84f)

Vamos comiencen luego con a darle forma al datadashboard...you can do it! :muscle:

**Comment by MirEnovi** [comment]
Antes que nada una disculpa,  por responder tan tarde. 
Tenemos los milestones y sus issues en el repositorio de @AuraMelisa01 , la hice colaboradora para que estos aparecieran en el repositorio master, pero tuvimos conflictos con los pull request y regresamos a la manera de trabajo anterior. Seguimos trabajando los issues en su cuenta. El día de hoy intentaremos pasarlos a la mía para que se puedan ver en ambos repositorios.
Ya hemos puesto la liga en nuestra pagina principal y hemos tratado de implementar el html semántico.
Gracias por las recomendaciones, a pesar de la tardía respuesta si las hemos estado aplicando.
ATTE: Mirian y Melisa.
